# Generated by Django 4.2.25 on 2025-10-23 11:21

import django.core.validators
from django.db import migrations, models
import userapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='phone must be start with +91 or 91 and after this must be 9/8/7/6', regex='^\\+?91[6-9]\\d{9}$')])),
                ('profile', models.ImageField(upload_to='profiles/', validators=[userapp.models.validate_profile, django.core.validators.FileExtensionValidator(['jpeg', 'png', 'jpg'])])),
            ],
        ),
    ]
