# Generated by Django 4.2.25 on 2025-10-27 10:39

import django.core.validators
from django.db import migrations, models
import userapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='profile',
            field=models.FileField(upload_to='profiles/', validators=[userapp.models.validate_profile, django.core.validators.FileExtensionValidator(['jpeg', 'png', 'jpg'])]),
        ),
    ]
